added tests for book repository
RedArtelerist/OnlineBookStore pull request #12
Opened 2023-11-11 15:30 UTC by RedArtelerist

2023-11-17 15:02 UTC, Elena-Bruyako requested changes
Good job! Left two comments

2023-11-17 15:02 UTC, Elena-Bruyako commented on src/test/java/maksym/fedorenko/bookstore/config/CustomMySqlContainer.java
> +
remove empty line

2023-11-17 15:02 UTC, Elena-Bruyako commented on src/test/java/maksym/fedorenko/bookstore/controller/BookControllerTest.java
> +
Let's add test for getAll books

2023-11-28 08:29 UTC, NazarSmith228 approved these changes
Good job! But please pay attention to my comments

2023-11-28 08:29 UTC, NazarSmith228 commented on src/test/java/maksym/fedorenko/bookstore/repository/BookRepositoryTest.java
> +            ScriptUtils.executeSqlScript(
in other tests you use `@Sql`

why not using it here as well?

2023-11-28 08:29 UTC, NazarSmith228 commented on src/test/java/maksym/fedorenko/bookstore/controller/CategoryControllerTest.java
> +    void getById_WithNonExistedId_BadRequest() throws Exception {
```suggestion
    void getById_WithNonExistedId_NotFound() throws Exception {
```

2023-11-28 09:27 UTC, merged